@localHost=127.0.0.1
@port=4000
@url=HTTP://{{localHost}}:{{port}}/CRUD

###

GET HTTP://{{localHost}}:{{port}}/

###

GET {{url}}

###

GET {{url}}/a

###

POST {{url}}/POST
Content-Type: application/json

{
    "Nome": "h",
    "Cognome": "s",
    "Indirizzo": 100,
    "Posta": "h.s"
}

###

DELETE {{url}}/test